### ISSUE TITLE
完整的代码

### ISSUE THREAD

**Issue by ZFU123456** [weix-liu/AFSP#1]
完整的代码什么时候公布？

**Comment by weix-liu** [comment]
现有版本即为完整代码，核心代码在lib.tar压缩包内请解压

**Comment by ZFU123456** [comment]
> 现有版本即为完整代码，核心代码在lib.tar压缩包内请解压

好滴，感谢！！！

**Comment by ZFU123456** [comment]
作者能否重新上传下VGG16 和ResNet101模型，链接已失效

**Comment by weix-liu** [comment]
VGG16 和ResNet101模型链接已更新
